services:
  db:
    image: postgres:16.3-alpine3.19
    volumes:
      - db-dev:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - 5432:5432
    restart: always

  db-migration:
    image: aryyadocker/swarm-orchestra-101-db-migrate:1.0
    volumes:
      - ./backend-service/db/migrations:/migrations
    env_file: ".env"
    command:
      ['-path=/migrations', '-database', '${POSTGRES_SOURCE}', '-verbose', 'up']
    depends_on:
      - db
    restart: on-failure

  backend:
    build:
      context: ./backend-service
    volumes:
      - ./backend-service:/app
    ports:
      - 8080:8080
    depends_on:
      - db-migration
    restart: always

  frontend:
    build:
      context: ./frontend-service
    ports:
      - 5173:5173
    volumes:
      - ./frontend-service:/app
    depends_on:
      - backend
    restart: always

volumes:
  db-dev:
