services:
  db:
    image: postgres:16.3-alpine3.19
    volumes:
      - db-production:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=swarm_orchestra_101
    restart: always
  
  db-migration:
    image: migrate/migrate:v4.17.1
    volumes:
      - ./backend-service/db/migrations:/migrations
    command: ["-path=/migrations", "-database", "${POSTGRES_SOURCE}", "-verbose", "up"]
    depends_on:
      - db

  backend:
    build:
      context: ./backend-service
      dockerfile: Dockerfile.production
    restart: always

  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile.production
      args:
        - "VITE_BACKEND_URL=${VITE_BACKEND_URL}"
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always

volumes:
  db-production: