services:
  db:
    image: postgres:16.3-alpine3.19
    volumes:
      - db-production:/var/lib/postgresql/data
    env_file: '.env.production'
    restart: always

  db-migration:
    image: migrate/migrate:v4.17.1
    volumes:
      - ./backend-service/db/migrations:/migrations
    env_file: '.env.production'
    command:
      ['-path=/migrations', '-database', '${POSTGRES_SOURCE}', '-verbose', 'up']
    depends_on:
      - db

  backend:
    image: aryyadocker/swarm-orchestra-101-backend-production:1.0
    restart: always

  frontend:
    image: aryyadocker/swarm-orchestra-101-frontend-production:1.0
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always

volumes:
  db-production:
